### ISSUE TITLE
Improving current code quality

### ISSUE THREAD

**Issue by manighahrmani** [tesliim07/truthtable#2]
[test.py](https://github.com/tesliim07/truthtable/blob/main/test.py) can be improved. Firstly, the function `truthTableDesign` only works for maximum of 6 inputs. Secondly, the code complexity is high due to, so many nested for loops. 

I suggest you look into 2d arrays in Python. Then write a function `populateColumn` that takes column number, total number of rows and the 2d array, and it inserts the 0 and 1s for that column in that array. E.g. populateColumn(2,4,array), where array is an array on 4 rows and 2 columnd filled with all 0s, will make array into: 
`
[
[0,0],
[0,1],
[0,0],
[0,1]
]
`

**Comment by tesliim07** [comment]
Sorry I haven’t been able to work on it cause I have covid and feeling really unwell but I will get to work on it as quickly as possible.

**Comment by tesliim07** [comment]
Is there a particular video you’ll suggest watching for the 2d arrays

**Comment by manighahrmani** [comment]
Sorry to hear that. You can talk to your supervisor and discuss submitting
an EC form, perhaps to get extension on cwk deadlines (you can submit your
covid test result as an evidence). Also, there is no deadline between me,
and you, so there is no rush, I was just outlining next steps.

Hope you get better soon,
Mani
